### ISSUE TITLE
User account is not working (Bug)

### ISSUE THREAD

**Issue by SergeyMC9730** [KrutosVIP/PyT#1]
```
Username: user
Traceback (most recent call last):
  File "kinit.py", line 48, in <module>
    main()
  File "kinit.py", line 22, in main
    boot_os()
  File "kinit.py", line 46, in boot_os
    kernel.BaseKernel(d["properties"])
  File "/home/dogo/PyT/kernel/kernel.py", line 65, in __init__
    self.startup()
  File "/home/dogo/PyT/kernel/kernel.py", line 106, in startup
    self.modules[self.info["shell"]].run(i)
  File "../mod/pyt2.py", line 125, in run
    print(self.color(f"{info[11]['pyt']['color']}{self.info['user']}@{info[8]}{Style.RESET_ALL} {self.cwd} $ "), end = "")
AttributeError: 'PyT2' object has no attribute 'cwd'
```

**Comment by KrutosVIP** [comment]
Thanks for your issue, I found this bug and fixed.
